-- INSERT TEST DATA

INSERT INTO 
`Country` (`Country`,`Remark`)
VALUES
('Ägypten','arabisch'),
('Argentinien','spanisch'),
('Australien','englisch'),
('Belgien','französisch'),
('Belgien','niederländisch'),
('Brasilien','portugiesisch'),
('Bulgarien','bulgarisch'),
('China','chinesisch'),
('Dänemark','dänisch'),
('Deutschland','deutsch'),
('England (Vereinigtes Königreich)','englisch'),
('Estland','estnisch'),
('Finnland','finnisch'),
('Frankreich','französisch'),
('Griechenland','griechisch'),
('Grönland','niederländisch'),
('Indien','bengalisch'),
('Indien','englisch'),
('Indonesien','indonesisch'),
('Irland','englisch'),
('Island','isländisch'),
('Italien','italienisch'),
('Japan','japanisch'),
('Kanada','französisch'),
('Kroatien','kroatisch'),
('Lettland','lettisch'),
('Liechtenstein','deutsch'),
('Litauen','litauisch'),
('Luxemburg','deutsch'),
('Monako','französisch'),
('Niederlande','friesisch'),
('Norwegen','Norwegisch'),
('Österreich','deutsch'),
('Polen','polnisch'),
('Portugal','portugiesisch'),
('Rumänien','rumänisch'),
('Schweden','schwedisch'),
('Schweiz','deutsch'),
('Senegal','französisch'),
('Slowakei','slovakisch'),
('Slowenien','slovenisch'),
('Spanien','spanisch'),
('Tschechien','tschechisch'),
('Türkei','türkisch'),
('Ungarn','ungarisch'),
('USA','englisch');
